name: tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install nightly rust (for rustfmt)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: install stable rust (for clippy)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-lint-

      - name: install cargo-deny
        run: command -v cargo-deny >/dev/null || cargo install --locked cargo-deny

      - name: run lints
        run: make lint

  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install nightly rust (for rustfmt)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: install stable rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-generate-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-generate-

      - name: install kopium
        run: command -v kopium >/dev/null || cargo install --locked kopium --version 0.22.5

      - name: run generate
        run: make generate

      - name: check for uncommitted changes
        run: git diff --exit-code

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-test-

      - name: run unit tests
        run: make test.unit

      - name: install kind
        run: |
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: run integration tests
        run: make test.integration
